# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build React App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: build_instance

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          echo "DevOps Engineer"
          echo ${{ github.workspace }}
          cd ${{ github.workspace }} ; npm install

      - name: Build
        run: |
          cd ${{ github.workspace }}
          npm run build
